# Exceptiontrap Config File

# If ENV['api-key'] is set, it will be used instead of the following api-key
# This happens for example, if you use the exceptiontrap addon on heroku
api-key: 3ccc472ef9fd7bb39d979c409fd1b0af
ssl: true
timeout: 5000
enabledEnvironments:
  - 'production'
ignoreExceptions:
  - 'ActiveRecord::RecordNotFound'
  - 'ActionController::RoutingError'
  - 'ActionController::InvalidAuthenticityToken'
  - 'CGI::Session::CookieStore::TamperedWithCookie'
  - 'ActionController::UnknownAction'
filterParams:
  - 'password'
  - 'password_confirmation'
  - 's3-key'